adventureworks:
  target: duckdb
  outputs:
    duckdb:
     type: duckdb
     path: target/adventureworks.duckdb
     threads: 12

     # duckdb target/adventureworks.duckdb
    # SELECT * FROM marts.fct_sales LIMIT 10;
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: adventureworks
      schema: dbo
      threads: 12
      
